# Démo pour les formats et les objet python

## String

In [1]:
st1 = 'GEO' # création d'un string
st2 = '71021'

string = '1'
i = 1

list = [1,'1',4.5]
print(type(list))
print(list)
print(type(i))
print(type(st1))
print(st1)
print(st2)
print(st1+st2)
print(len(st1))

#comparaison
if st1 == st2:
    print('les strings sont identiques')
    
else:
    print('les strings sont différents')

        

<class 'list'>
[1, '1', 4.5]
<class 'int'>
<class 'str'>
GEO
71021
GEO71021
3
les strings sont différents


## Built_in methods for strings

In [3]:
print(st1.lower())
print(type(st1))
print(st1.rfind('G'))

geo
<class 'str'>
0


## integer

In [6]:
it1 = 4 #création d'un integer
it2 = 6
print(type(it1))

print(it1 + it2)
print( it1/it2)
print(type(it1/it2))
print(int(it1/it2))
print(it1*it2)
print(it1**it2)

#comparaison
if it1 > it2:
    print(str(it1) + ' plus grand que ' + str(it2))
else:
    print(str(it1) + ' plus petit que ' + str(it2))

<class 'int'>
10
0.6666666666666666
<class 'float'>
0
24
4096
4 plus petit que 6


## List

In [15]:
li1 = [st1, st2, it1, it2] #Création de la liste
print(li1)

li2 = ['Bay', 'Felix', 'Jean-Gab', 'Julie', 'Sam']
print(li2)

#Comment ajouter mon nom à la liste du cours?
li2.append('francis')
print(li2)

#Combien d'élément compose la liste?
resultat_len = len(li2)
print(resultat_len)

#Comment faire pour aller chercher le 3ième élement de la list?
li2[2]
print(li2[2])
#Comment faire pour aller chercher le dernier élement de la list?
print(li2[-1])
#Comment obtenir le deuxième élément jusqu'à l'avant dernier?
li2[1:4]

['GEO', '71021', 4, 6]
['Bay', 'Felix', 'Jean-Gab', 'Julie', 'Sam']
['Bay', 'Felix', 'Jean-Gab', 'Julie', 'Sam', 'francis']
6
Jean-Gab
francis


['Felix', 'Jean-Gab', 'Julie']

## Dictionnaire

In [16]:
dictio1 = {'etudiant1': 'francis', 'etudiant2': 'David'}
print(dictio1)

#Comment obtenir le nom de l'etudiant2?
print(dictio1['etudiant2'])

#Comment ajouter un élément au dictionnaire
dictio1['etudiant3'] = 'Jean-Gab'
print(dictio1)


{'etudiant1': 'francis', 'etudiant2': 'David'}
David
{'etudiant1': 'francis', 'etudiant2': 'David', 'etudiant3': 'Jean-Gab'}


## Interaction

In [17]:
list_int = ['Francis', 28, 'David', 30.5, True]
list_int

['Francis', 28, 'David', 30.5, True]

## Imbrication

In [19]:
list_imb = [[2,3,6,89,652,5,26,2,4,6],[25,35,68,74,5,7,98,6,86,2],[7,8,9,4,65,235,41,256,12,23]]
print(list_imb)

#comment récupérer la 2 list dans la list?
print(list_imb[1])

#Comment récupérer la 6 éléments de la 3ième list?
print(list_imb[2][5])

[[2, 3, 6, 89, 652, 5, 26, 2, 4, 6], [25, 35, 68, 74, 5, 7, 98, 6, 86, 2], [7, 8, 9, 4, 65, 235, 41, 256, 12, 23]]
[25, 35, 68, 74, 5, 7, 98, 6, 86, 2]
235


In [20]:
# Imbrication de dictionnaire et de liste
dictli = {'profil_1':[2,3,6,89,652,5,26,2,4,6], 'profil_2':[25,35,68,74,5,7,98,6,86,2], 'profil_3': [7,8,9,4,65,235,41,256,12,23]}
print(dictli)

#comment récupérer le profil 2 dans la list?
print(dictli['profil_2'])

#Comment récupérer la 6 éléments du profil numéro 3?
print(dictli['profil_3'][5])

{'profil_1': [2, 3, 6, 89, 652, 5, 26, 2, 4, 6], 'profil_2': [25, 35, 68, 74, 5, 7, 98, 6, 86, 2], 'profil_3': [7, 8, 9, 4, 65, 235, 41, 256, 12, 23]}
[25, 35, 68, 74, 5, 7, 98, 6, 86, 2]
235


## NumPY

In [ ]:
import numpy as np
from scipy 

In [ ]:
#Création d'une numpy array à partir d'une liste python
arr1d = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr1d)
print(arr1d.shape)

#Création d'une numpy array à partir de linspace
# on veut créer un array de 0 à 10, avec un intervalle de 0.5
arr1d_5 = np.linspace(0, 10, 21) #pourquoi 21?
print(arr1d_5)
print(arr1d_5.shape)
print(arr1d_5.ndim)


## Shape et dimension

In [ ]:
arr2d = np.array([[1,2,3],
                [1,2,3],
                [1,2,3]])
print(arr2d)
print(arr2d.shape)
print(arr2d.ndim)

In [ ]:
arr3d = np.array([[[1,2,3],
                   [1,2,3],
                   [1,2,3]],
                   [[1,2,3],
                   [1,2,3],
                   [1,2,3]],
                   [[1,2,3],
                   [1,2,3],
                   [1,2,3]]])
print(arr3d)
print(arr3d.shape)
print(arr3d.ndim)

# Operations sur un numpy array

In [23]:
import numpy as np

In [24]:
# addition de deux list python
l1 = [1,2,3,4]
l2 = [1,1,1,1]
print(l1 + l2)

# addition de deux numpy array
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,1,1,1])
print(arr1 + arr2)

#Quelle ligne de code plus simple nous donnerait le même array équivalent?
arr1+1

[1, 2, 3, 4, 1, 1, 1, 1]
[2 3 4 5]


array([2, 3, 4, 5])

In [26]:
#créer un array vertical de shape (6,1) (2 dimensions obligatoire pour le verticale)
a0 = np.array([0,10,20,30,40,50])
a0 = a0.reshape([6,1])
print(a0.shape)
print(a0)

#Je crée un array horizontal de shape (3,0) (1 dimensions)
a1 = np.array([0,1,2])
print(a1.shape)
print(a1)

#addition de broadcast
a_add = a0 + a1
print(a_add)

#multiplication de broadcast
a_mult = a0 * a1
print(a_mult)

(6, 1)
[[ 0]
 [10]
 [20]
 [30]
 [40]
 [50]]
(3,)
[0 1 2]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]
 [40 41 42]
 [50 51 52]]
[[  0   0   0]
 [  0  10  20]
 [  0  20  40]
 [  0  30  60]
 [  0  40  80]
 [  0  50 100]]


## Pandas DataFrame

In [27]:
import pandas as pd

In [ ]:
# Créer un dictionnaire
d = {'profil_1': [1,2,3,4,5,6], 'profil_2':[7,8,9,10,11,12]}
# Création d'un dataframe avec un dictionnaire
df = pd.DataFrame(d)
df

In [28]:
# Créer un dataframe à partir d'un csv
# La fonction nécéssite un filepath en intrant
df_csv = pd.read_csv('/home/francis/Documents/UQAR/Cours/GEO71021/data_exemple/Epaule_20201006.csv')
df_csv

index     name  longitude   latitude   elevation         collection start  \
0      1  Point 1 -66.150767  48.911191  571.358885  2020-10-06 14:27:02 UTC   
1      2  Point 2 -66.151050  48.911376  586.675706  2020-10-06 14:31:35 UTC   
2      3  Point 3 -66.150732  48.911728  589.224440  2020-10-06 14:36:37 UTC   
3      4  Point 4 -66.150279  48.912228  588.473287  2020-10-06 14:44:52 UTC   
4      5  Point 5 -66.150332  48.911692  573.363618  2020-10-06 14:50:50 UTC   
5      6  Point 6 -66.150291  48.911384  565.238279  2020-10-06 14:54:09 UTC   

            collection end solution status  lateral rms  sample count  \
0  2020-10-06 14:27:39 UTC             FIX       0.0159         187.0   
1  2020-10-06 14:32:00 UTC             FIX       0.0072         126.0   
2  2020-10-06 14:37:04 UTC             FIX       0.0102         136.0   
3  2020-10-06 14:45:14 UTC             FIX       0.0079         112.0   
4  2020-10-06 14:51:23 UTC             FIX       0.0083         167.0   
5  2020-10-06 14:54:35 UTC             FIX       0.0090         126.0   

   antenna height  
0           2.134  
1           2.134  
2           2.134  
3           2.134  
4           2.134  
5           2.134

In [30]:
# Comment sélectionner des données dans un pandas dataframe?
# Slicing
print(df_csv[0:2])# noter que le dernier index est exclusif
df_csv['elevation'][0:2]

   index     name  longitude   latitude   elevation         collection start  \
0      1  Point 1 -66.150767  48.911191  571.358885  2020-10-06 14:27:02 UTC   
1      2  Point 2 -66.151050  48.911376  586.675706  2020-10-06 14:31:35 UTC   

            collection end solution status  lateral rms  sample count  \
0  2020-10-06 14:27:39 UTC             FIX       0.0159         187.0   
1  2020-10-06 14:32:00 UTC             FIX       0.0072         126.0   

   antenna height  
0           2.134  
1           2.134  


0    571.358885
1    586.675706
Name: elevation, dtype: float64

In [31]:
# Il existe déjà une colonne index. On peut l'utiliser pour setter un index personnalisé
# Cela peu être utile si on veut indexer avec un index temporel
df_csv.set_index('collection start')

index     name  longitude   latitude   elevation  \
collection start                                                            
2020-10-06 14:27:02 UTC      1  Point 1 -66.150767  48.911191  571.358885   
2020-10-06 14:31:35 UTC      2  Point 2 -66.151050  48.911376  586.675706   
2020-10-06 14:36:37 UTC      3  Point 3 -66.150732  48.911728  589.224440   
2020-10-06 14:44:52 UTC      4  Point 4 -66.150279  48.912228  588.473287   
2020-10-06 14:50:50 UTC      5  Point 5 -66.150332  48.911692  573.363618   
2020-10-06 14:54:09 UTC      6  Point 6 -66.150291  48.911384  565.238279   

                                  collection end solution status  lateral rms  \
collection start                                                                
2020-10-06 14:27:02 UTC  2020-10-06 14:27:39 UTC             FIX       0.0159   
2020-10-06 14:31:35 UTC  2020-10-06 14:32:00 UTC             FIX       0.0072   
2020-10-06 14:36:37 UTC  2020-10-06 14:37:04 UTC             FIX       0.0102   
2020-10-06 14:44:52 UTC  2020-10-06 14:45:14 UTC             FIX       0.0079   
2020-10-06 14:50:50 UTC  2020-10-06 14:51:23 UTC             FIX       0.0083   
2020-10-06 14:54:09 UTC  2020-10-06 14:54:35 UTC             FIX       0.0090   

                         sample count  antenna height  
collection start                                       
2020-10-06 14:27:02 UTC         187.0           2.134  
2020-10-06 14:31:35 UTC         126.0           2.134  
2020-10-06 14:36:37 UTC         136.0           2.134  
2020-10-06 14:44:52 UTC         112.0           2.134  
2020-10-06 14:50:50 UTC         167.0           2.134  
2020-10-06 14:54:09 UTC         126.0           2.134

In [32]:
# Comment séléectionner par une colonne
df_csv['longitude']

#Comment sélectionner une colonne et une rangée
print(df_csv['longitude'][2])

#Comment sélectionner une rangée et plus bas
#Rajoute le signe :
df_csv['longitude'][2:]

-66.15073172729412


2   -66.150732
3   -66.150279
4   -66.150332
5   -66.150291
Name: longitude, dtype: float64

## Concatenate, Merge and join Pandas

In [ ]:
left = pd.DataFrame(
        {'keys':['p1','p2','p3','p4','p5'],
        'lat':[43.12,42.97,43.54,43.16,43.04], 
        'long':[-111.32,-111.23,-111.41,-111.05,-111.08],
        'alt':[125,112,108,97,138]}
)
right = pd.DataFrame(
        {'keys':['p1','p1','p1','p2','p2','p3','p4','p6'],
         'temp':[15,14,12,23,16,18,13,11],
         'HR':[98,91,92,95,98,93,91,93]}
)
print(left)
print(right)

#concatenate axis 1
con1 = pd.concat([left,right], axis=1)
print(con1)

In [ ]:
#merge join left
merg1 = pd.merge(left,right, how='left', on='keys')
print(merg1)

In [ ]:
#merge join right
merg2 = pd.merge(left,right, how='right', on='keys')
print(merg2)

In [ ]:
#merge join inner
mergin = pd.merge(left,right, how='inner', on='keys')
print(mergin)

In [ ]:
#merge join outter
mergout = pd.merge(left,right, how='outer', on='keys')
print(mergout)

## GeoPandas

In [ ]:
import geopandas as gpd

In [ ]:
#string de mon file path de mon shpfile
shpfile = '/home/francis/Documents/UQAR/Cours/GEO71021/data_exemple/EP_20200229_postcorrected.shp'

#lecture de mon shpfile avec comme paramètre mon objet string contenant mon filepath
shp_gpd = gpd.read_file(shpfile)
shp_gpd

In [ ]:
# Obtenir l'information du CRS
print(shp_gpd.crs)

#Reprojeter en utm avec le code EPSG de UTM zone 19
point_26919 = shp_gpd.to_crs(26919)
point_26919

## Rasterio

In [ ]:
import rasterio
from rasterio.plot import show #limite l'importation de la libairie
import matplotlib.pyplot as plt

In [ ]:
raster = rasterio.open('/home/francis/Documents/UQAR/Cours/GEO71021/data_exemple/TPI_EP.sdat')
print(raster.crs)
show(raster)

In [ ]:
#Créer une figure plus grande
fig, ax = plt.subplots(figsize=(20,20))
point_26919.plot(ax=ax, color='orangered') # Ajout des points d'échantillonnage sur la figure
show(raster, ax=ax)

## For Loop

In [ ]:
l = range(10)
print(l)

for i in range(10):
    print(i)
    print('allo numéro '+str(i))
    if i < 5 & :
        print('yes')
    else:
        print('fuck')

In [ ]:
l = ['francis', 'felix', 'bay', 'sam', 'julie']

for i in l:
    print('nombre de lettre dans '+i+' : '+ str(len(i)))

In [ ]:
#for loop d'un dictionnaire le i représente quoi?
for i in dictli:
    print(i)

In [ ]:
# les profils contiennent des list de valeurs que j'aimerais également parcourir

for key, items in dictli.items():
    print(key)
    print(items)
    for i in items:
        print(i)
        
        

In [ ]:
#Stockage de l'opération de notre for loop et condition
coord = {}
for index, row in point_26919.iterrows():
    print('index ' + str(index))
    print('nb_sample ' + str(row['nb_sample']))
    if row['nb_sample'] >= 60:
        print('yessir miller')
    else:
        print('merde')
    x = row['geometry'].xy[0][0]
    y = row['geometry'].xy[1][0]
    name = row['point_id']
    coord.update({name:[x,y]})


In [ ]:
coord

## Fonction

In [ ]:
def my_function(filename,nb_sample):
    gdf = gpd.read_file(filename)
    gdf_26919 = gdf.to_crs(26919)
    
    coord = {}
    for index, row in gdf.iterrows():
        print('index ' + str(index))
        print('nb_sample ' + str(row['nb_sample']))
        if row['nb_sample'] >= nb_sample:
            print('yessir miller')
        else:
            print('merde')
        x = row['geometry'].xy[0][0]
        y = row['geometry'].xy[1][0]
        name = row['point_id']
        coord.update({name:[x,y]})
    return coord

In [ ]:
def my_function(fileshpf,fileraster):
    gdf = gpd.read_file(filename)
    gdf_26919 = gdf.to_crs(26919)
    
    coord = []
    for index, row in gdf.iterrows():
        x = row['geometry'].xy[0][0]
        y = row['geometry'].xy[1][0]
        name = row['point_id']
        
        values = float(xdr.sel(x = x, y = y, method = "nearest").values)
        print(values)
        coord.append(values)
        #coord.update({name:[x,y]})
    return coord

In [ ]:
path = '/home/francis/Documents/UQAR/Cours/GEO71021/data_exemple/EP_20200229_postcorrected.shp'

EP_coord = my_function(path, 80) 
EP_coord


In [ ]:
path_shpf = '/home/francis/Documents/UQAR/Cours/GEO71021/data_exemple/EP_20200229_postcorrected.shp'
path_raster = 'dd'
EP_coord = my_function(path_shpf, path_raster) 
EP_coord